# Generated by Django 5.2.3 on 2025-06-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
